"""create files table

Revision ID: 872eccc8445e
Revises: 731d6af17fd5
Create Date: 2026-08-28 11:03:31.365964

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "872eccc8445e"
down_revision: str | None = "731d6af17fd5"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum("file", "folder", name="file_type", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_files_parent_id"), "files", ["parent_id"], unique=False)
    op.create_index(op.f("ix_files_project_id"), "files", ["project_id"], unique=False)
    op.create_index(
        "ix_files_unique_child_name",
        "files",
        ["project_id", "parent_id", "name"],
        unique=True,
        postgresql_where="parent_id IS NOT NULL",
    )
    op.create_index(
        "ix_files_unique_root_name",
        "files",
        ["project_id", "name"],
        unique=True,
        postgresql_where="parent_id IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_files_unique_root_name", table_name="files", postgresql_where="parent_id IS NULL"
    )
    op.drop_index(
        "ix_files_unique_child_name", table_name="files", postgresql_where="parent_id IS NOT NULL"
    )
    op.drop_index(op.f("ix_files_project_id"), table_name="files")
    op.drop_index(op.f("ix_files_parent_id"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
